name: aitai
description: "A new Flutter project."
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '^3.3.0'
  
dependencies:
  provider: ^6.1.2
  flutter_hooks:
  web_socket_channel:
  google_fonts:
  device_preview:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  json_annotation:
  freezed_annotation:
  percent_indicator:
  go_router: ^13.2.2
  
  pixel_color_image:
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  google_sign_in:
  cloud_firestore: ^4.15.6
  firebase_analytics: ^10.8.7
  intl: ^0.18.1
  flutter_web_plugins:
    sdk: flutter
  firebase_database: ^10.4.10
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  avatar_glow: ^2.0.2
  speech_to_text: ^6.6.1
  shared_preferences: ^2.2.2
  hooks_riverpod: ^2.5.1
  uuid: ^4.3.3
  flutter_signin_button: ^2.0.0
  firebase_messaging: ^14.8.0

dev_dependencies:
  freezed:
  build_runner:
  flutter_lints:
  riverpod_generator:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_fonts/
