name: aitai
description: "A new Flutter project."
version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
 # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
environment:
  sdk: '^3.3.0'
  
dependencies:
  provider: ^6.1.2
  flutter_hooks:
  web_socket_channel:
  google_fonts:
  device_preview:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  json_annotation:
  freezed_annotation:
  percent_indicator:
  go_router: ^13.2.2
  
  pixel_color_image:
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  google_sign_in:
  cloud_firestore: ^4.15.6
  firebase_analytics: ^10.8.7
  intl: ^0.18.1
  flutter_web_plugins:
    sdk: flutter
  firebase_database: ^10.4.10
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  avatar_glow: ^2.0.2
  speech_to_text: ^6.6.1
  shared_preferences: ^2.2.2
  hooks_riverpod: ^2.5.1
  uuid: ^4.3.3
  flutter_signin_button: ^2.0.0
  firebase_messaging: ^14.8.0

dev_dependencies:
  freezed:
  build_runner:
  flutter_lints:
  riverpod_generator:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_fonts/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# firebaseのバージョンが原因でエラーが発生しました。次からは気を付けよう！！

# firebase関連でエラーが発生しているっぽいな
# <key>タグに続くのは必ず<string>
# name: aitai
# description: "A new Flutter project."
# # The following line prevents the package from being accidentally published to
# # pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# # The following defines the version and build number for your application.
# # A version number is three numbers separated by dots, like 1.2.43
# # followed by an optional build number separated by a +.
# # Both the version and the builder number may be overridden in flutter
# # build by specifying --build-name and --build-number, respectively.
# # In Android, build-name is used as versionName while build-number used as versionCode.
# # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# # In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# # Read more about iOS versioning at
# # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# # In Windows, build-name is used as the major, minor, and patch parts
# # of the product and file versions while build-number is used as the build suffix.
# version: 1.0.0+1

# environment:
#   sdk: ^3.0.0

# # Dependencies specify other packages that your package needs in order to work.
# # To automatically upgrade your package dependencies to the latest versions
# # consider running `flutter pub upgrade --major-versions`. Alternatively,
# # dependencies can be manually updated by changing the version numbers below to
# # the latest version available on pub.dev. To see which dependencies have newer
# # versions available, run `flutter pub outdated`.
# dependencies:
#   google_generative_ai:
#   file_picker:
#   arkit_plugin:
#   flutter:
#     sdk: flutter
#   flutter_riverpod:
#   flutter_hooks:
#   riverpod_annotation:
#   google_fonts:
#   flutter_slidable:
#   json_annotation:
#   freezed_annotation:
#   liveroom:
#   percent_indicator:
#   go_router:
#   pixel_color_image:
#   web_socket_channel:
#   firebase_core: ^2.24.2
#   firebase_analytics:
#   firebase_auth:
#   google_sign_in:
#   device_preview_minus: # device_preview が開発停止したため代わりに使う
#   envied:
#   shared_preferences:
#   cloud_firestore:
#   intl:
#   youtube_player_iframe:
#   url_launcher:
#   flutter_web_plugins:
#     sdk: flutter

# dev_dependencies:
#   freezed:
#   build_runner:
#   json_serializable:
#   flutter_test:
#     sdk: flutter
#   flutter_lints:
#   riverpod_generator:
#   envied_generator:

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
  